using DV.Logic.Job;
using DV.ThingTypes;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace DLE.Jobs
{
    public static class JobUtils
    {
        // Per-route counters so each origin-dest pair gets its own sequence:
        //   SM-HB-01, SM-HB-02 ...  HB-MF-01 ...  HB-CS-01 ...
        private static readonly Dictionary<string, int> _routeCounters =
            new Dictionary<string, int>(System.StringComparer.Ordinal);

        /// <summary>
        /// Set of job IDs generated by DLE. Patches check this to tell our jobs
        /// apart from vanilla ones.
        /// </summary>
        public static readonly HashSet<string> ManagedJobIds =
            new HashSet<string>(System.StringComparer.Ordinal);

        /// <summary>
        /// Generate the next job ID for a given route in DV-style format:
        /// "{originYardId}-{destYardId}-{NN}" e.g. "SM-HB-01", "HB-MF-03".
        /// Counter wraps 01-99 per route and resets to 01 on overflow.
        /// </summary>
        public static string NextId(string originYardId, string destYardId)
        {
            var key = $"{originYardId}-{destYardId}";
            _routeCounters.TryGetValue(key, out var count);
            count = (count % 99) + 1;          // 1-99, then back to 1
            _routeCounters[key] = count;

            var id = $"{originYardId}-{destYardId}-{count:D2}";
            ManagedJobIds.Add(id);
            return id;
        }

        /// <summary>
        /// After restoring a saved job like "SW-SM-03", make sure the route counter is past
        /// 03 so newly generated IDs cannot collide, and re-register the ID as managed.
        /// </summary>
        public static void EnsureCounterPast(string jobId)
        {
            ManagedJobIds.Add(jobId);
            var lastDash = jobId.LastIndexOf('-');
            if (lastDash <= 0) return;
            var key = jobId.Substring(0, lastDash);
            if (!int.TryParse(jobId.Substring(lastDash + 1), out var n)) return;
            _routeCounters.TryGetValue(key, out var cur);
            if (n > cur) _routeCounters[key] = n;
        }

        public static StationsChainData Chain(string originYardId, string destYardId) =>
            new StationsChainData(originYardId, destYardId);

        // Wage / time estimates (rough; fine-tuned later)

        public static float EstimateWage(int carCount, float distanceFactor = 1f) =>
            Mathf.Max(200f, carCount * 450f * distanceFactor);

        public static float EstimateTimeLimit(int carCount, float distanceFactor = 1f) =>
            Mathf.Max(600f, carCount * 120f * distanceFactor + 600f);

        // JobChainController builder

        /// <summary>
        /// Wrap a StaticJobDefinition in a JobChainController, finalize it,
        /// and register it with the station's procedural controller.
        /// Note: JobChainController is NOT a MonoBehaviour; it is a plain class.
        /// responsibleStationForJobChain is private in DV and surfaced via Publicizer.
        /// </summary>
        public static JobChainController ActivateJobChain(
            StaticJobDefinition def,
            StationController station)
        {
            var jcc = new JobChainController(def.gameObject);
            jcc.responsibleStationForJobChain = station;
            if (def is StaticTransportJobDefinition transport && transport.carsToTransport != null)
                jcc.carsForJobChain = transport.carsToTransport;
            jcc.AddJobDefinitionToChain(def);
            try
            {
                jcc.FinalizeSetupAndGenerateFirstJob(false);
            }
            catch (System.Exception ex)
            {
                // If job generation fails, destroy the partial JCC and its GameObject so it
                // doesn't corrupt autosave ("Uninitialized chain controller!").
                Main.LogAlways($"[JobUtils] ActivateJobChain failed ({ex.GetType().Name}): {ex.Message}");
                try { jcc.DestroyChain(); } catch { }
                UnityEngine.Object.Destroy(def.gameObject);
                return null;
            }
            station.ProceduralJobsController.AddJobChainController(jcc);
            return jcc;
        }

        // Car helpers

        public static List<Car> ToLogicCars(IEnumerable<TrainCar> trainCars) =>
            TrainCar.ExtractLogicCars(trainCars.ToList());

        public static List<CargoType> GetCargoes(IEnumerable<TrainCar> cars) =>
            cars.Select(c => c.logicCar.CurrentCargoTypeInCar).ToList();

        public static List<float> GetCargoAmounts(IEnumerable<TrainCar> cars) =>
            cars.Select(c => c.logicCar.LoadedCargoAmount).ToList();

        /// <summary>
        /// Find the logic Track the majority of cars in a list are sitting on.
        /// </summary>
        public static Track FindCommonTrack(List<TrainCar> cars)
        {
            if (cars == null || cars.Count == 0) return null;
            return cars
                .Select(c => c.logicCar.CurrentTrack)
                .Where(t => t != null)
                .GroupBy(t => t)
                .OrderByDescending(g => g.Count())
                .Select(g => g.Key)
                .FirstOrDefault();
        }
    }
}
